### ISSUE TITLE
Error with Cast AIP 8.3.7 

### ISSUE THREAD

**Issue by FrancoNesci** [CASTResearchLabs/com.castsoftware.labs.green#1]
I can not install this extension on version 8.3.7.
I found 2 syntax errors on the GreenIT_ServerData.xml file:
- Could not merge the assessment model 'CAST 8.3.7 Assessment Model'. Reason: Bad XML content M: \ Cast \ Cast_Configuration \ Extensions \ com.castsoftware.labs.green.2.1.0 \ InstallScripts \ Common \ CRL / GreenIT_ServerData.xml - Invalid encoding name "utf-8?"
- Could not merge the assessment model 'CAST 8.3.7 Assessment Model'. Reason: Bad XML content M: \ Cast \ Cast_Configuration \ Extensions \ com.castsoftware.labs.green.2.1.0 \ InstallScripts \ Common \ CRL / GreenIT_ServerData.xml - For input string: "20140525 ("
Did I correct the GreenIT_ServerData.xml file by removing the character "?" and by I repeat the installation.
[CAST-MS-20190104-092507.log.txt](https://github.com/CASTResearchLabs/com.castsoftware.labs.green/files/2726564/CAST-MS-20190104-092507.log.txt)
[CAST-MS-20190104-092507.log.txt](https://github.com/CASTResearchLabs/com.castsoftware.labs.green/files/2726565/CAST-MS-20190104-092507.log.txt)

 I now have the error:
- Could not merge the assessment model 'CAST 8.3.7 Assessment Model'. Reason: null

Attached :
- CAST-MS-20190104-092507.log.txt
- GreenIT_ServerData.xml

Regards
Franco.

**Comment by CASTResearchLabs** [comment]
AIP 8.3 does not support creating new Technical Criteria and Business Criteria using existing Quality Rules anymore.
By the way, can you share your feedback about the extension? What was the perceived value of the findings? What should be added/removed to the computation in your opinion?
